### ISSUE TITLE
Seems broken with newest Ruby and/or deps

### ISSUE THREAD

**Issue by sjuvonen** [msrose/gfm#4]
I don't have any experience with Ruby, so I can't help any other way, but I get this error when trying to render a simple markdown file.

```
/home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline/filter.rb:160:in `needs': Missing context keys for HTML::Pipeline::HttpsFilter: :http_url (ArgumentError)                                                                                                     
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline/https_filter.rb:23:in `validate'                        
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline/filter.rb:42:in `initialize'                            
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline/filter.rb:130:in `new'                                  
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline/filter.rb:130:in `call'                                 
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline.rb:121:in `block in perform_filter'                     
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline.rb:159:in `instrument'                                  
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline.rb:120:in `perform_filter'                              
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline.rb:106:in `block (2 levels) in call'                    
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline.rb:105:in `each'                                        
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline.rb:105:in `inject'                                      
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline.rb:105:in `block in call'                               
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline.rb:159:in `instrument'                                  
        from /home/samu/.gem/ruby/2.2.0/gems/html-pipeline-2.0/lib/html/pipeline.rb:103:in `call'                                        
        from /home/samu/.gem/ruby/2.2.0/gems/gfm-0.1.5/lib/gfm/converter.rb:44:in `parse_markdown'                                       
        from /home/samu/.gem/ruby/2.2.0/gems/gfm-0.1.5/lib/gfm/converter.rb:35:in `html_content'                                         
        from /home/samu/.gem/ruby/2.2.0/gems/gfm-0.1.5/lib/gfm/converter.rb:12:in `write_output_file'                                    
        from /home/samu/.gem/ruby/2.2.0/gems/gfm-0.1.5/bin/gfm:13:in `<top (required)>'                                                  
        from /home/samu/.gem/ruby/2.2.0/bin/gfm:23:in `load'                                                                             
        from /home/samu/.gem/ruby/2.2.0/bin/gfm:23:in `<main>'
```

**Comment by msrose** [comment]
Could very well be a ruby version problem, since I v0.1.5 was developed with ruby 1.9.3 :stuck_out_tongue: (I recall testing it with an early 2.0 patch as well.)

It might even be an issue with the latest version of html-pipeline since for some reason I never specified the dependency versions in the gemspec...

Been meaning to update the gem for a while so I'll try and give it a look soon.
